- 대부분의 프로그래밍 언어는 프로그램에서 발생하는 오류에 대비하기 위해 오류를 처리하는 기능을 제공한다. 스위프트도 오류를 적절히 처리할 수 있는 기능을 제공한다.

# 1. 오류처리(Error Handling)란
- 오류처리는 프로그램이 오류를 일르켰을 때 이것을 감지하고 회복시키는 일련의 과정이다. 
- 프로그램에서 모든 기능이 우리가 원하는대로 100% 정확히 동작한다는 보장은 없다. 특히나 전달받아야 하는 값이 까다롭거나 데이터를 가공하는 데 소비하는 자원이 많을 경우 오류가 발생할 확률이 높아진다. 이런 가능성이 있는 기능을 구현할 때는 오류가 발생할 수 있음을 항상 고려해야 한다.
- 파일이 존재하지 않을 수도 있으며, 읽기 권한이 없을 수도 있고, 잘못된 파일일 가능성도 있다. 이렇게 파일을 읽어오는 간단한 기능에서도 오류가 발생할 수 있는 가능성이 여럿 존재한다. 오류처리 기능을 통해 이런 상황들을 구별하여 프로그램 자체적으로 오류를 해결할 수도 있고, 사용자와 상호작용을 통해 오류를 어떤 방향으로 풀어나갈지 제어할 수도 있습니다.
- 다만 주의할 점은 스위프트의 오류처리 기능을 통해 시스템(예를 들어 운영체제 등 우리가 작성하는 응용프로그램 외부)에서 발생한 오류를 처리할 수 있는 것이 아니다.

<br/>

-------------
# 2. 오류의 표현
- 스위프트에서 오류는 Error라는 프로토콜을 준수하는 타입의 값을 통해 표현된다. Error 프로토콜은 사실상 요구사항이 없는 빈 프로토콜일 뿐이지만, 오류를 표현하기 위한 타입(주로 열거형)은 이 프로토콜을 채택한다. 스위프트의 열거형은 오류의 종류를 나타내기에 아주 적합한 기능이다. 연관값을 통해 오류에 관한 부가 정보를 제공할 수도 있다. 
- 오류의 종류를 미리 예상한 다음, 오류 때문에 다음에 행할 동작이 정상적으로 진행되지 않을 때라면 오류를 던져(throw Error)주면 된다. 오류를 던져줄 때는 throw 구문을 사용한다.

<br/>

-------------
# 3. 오류 포착 및 처리
- 오류를 던질 수도 있지만 오류가 던져지는 것에 대비하여 던져진 오류를 처리하기 위한 코드도 작성해야한다. 예를 들어 던져진 오류가 무엇인지 판단하여 다시 문제를 해결한다든지, 다른 방법으로 문제 해결을 시도해 본다든지, 오류를 알리고 사용자에게 선택 권한을 넘겨주어 다음에 어떤 동작을 하게 할 것인지 결정하도록 유도하는 등의 코드를 작성해야한다.
- 스위프트에는 오류를 처리하기 위한 네 가지 방법이 있다.
  1. 함수에서 발생한 오류를 해당 함수를 호출한 코드에 알리는 방법
  2. do-catch 구문을 이용하여 오류를 처리하는 방법
  3. 옵셔널 값으로 오류를 처리하는 방법
  4. 오류가 발생하지 않을 것이라고 확신하는 방법

## 3.1. 함수에서 발생한 오류 알리기
- 먼저 함수에서 발생한 오류를 해당 함수를 호출한 코드에 알리는 방법이다. 함수가 오류를 던지면 프로그램의 흐름이 바뀐 가능성이 매우 크다. 그러므로 어디서 오류를 던지고 받을 것인가 결정하는 것은 매우 중요하다. try 키워드로 던져진 오류를 받을 수 있다. try 키워드는 try?, try! 등으로 표현할 수 있다.
- 함수, 메서드, 이니셜라이저의 매개변수 뒤에 throws 키워드를 사용하면 해당 함수, 메서드, 이니셜라이저는 오류를 던질 수 있다. 이러한 함수는 호출했을 때, 동작 도중 오류가 발생함녀 자신을 호출한 코드에 오류를 던져서 오류를 알릴 수 있다.

## 3.2. do-catch 구문을 이용하여 오류처리
- 함수, 메서드, 이니셜라이저등에서 오류를 던져주면 오류 발생을 전달받은 코드 블록은 do-catch 구문을 사용하여 오류를 처리해줘야한다. do절 내부의 코드에서 오류를 던지면 catch 절에서 오류를 전달받아 적절이 처리하면된다. 

## 3.3. 옵셔널 값으로 오류처리
- try?를 사용하여 옵셔널 값으로 변환하여 오류를 처리할 수도 있다. try? 표현을 통해 동작하던 코드가 오류를 던지면 그 코드의 반환 값은 nil이 된다.
- try? 표현을 사용하여 호출한 함수가 오류를 던지면 반환 값이 nil로 반환되고, 오류가 발생하지 않으면 옵셔널 값으로 반환된다. 

## 3.4. 오류가 발생하지 않을 것이라고 확신하는 방법
- 오류를 처리하는 마지막 방법으로는 오류가 발생하지 않을 것이라는 확신을 갖고 처리하는 방법이다. 코드를 작성하는 프로그래머가 오류를 던질 수 있는 함수 등을 호출할 때 오류가 절대로 발생하지 않을 것이라고 확신할 수 있는 상황이라면 오류가 발생하지 않을 것이라는 전제하에 try! 표현을 사용할 수 있다. 이표현은 다른 느낌표 표현(암시적 추출 옵셔널, 강제 타입캐스팅 등)과 마찬가지로 실제 오류가 발생하면 런타임 오류가 발생하여 프로그램이 강제로 종료된다.

## 3.5. 다시 던지기
- 함수나 메서드는 rethrows 키워드를 사용하여 자신의 매개변수로 전달받은 함수가 오류를 던진다는 것을 나타낼수 있다. rethrows 키워드를 사용하여 다시 던지기(Rethrowing)가 가능하게 하려면 최소 하나 이상의 오류 발생 가능한 함수를 매개변수로 전달받아야한다. 
- 다시 던지기 함수 또는 메서드는 기본적으로 스스로 오류를 던지지 못한다. 즉, 자신 내부에 직접적으로 throw 구문을 사용할 수 없다. 그러나 catch 절 내부에서는 throw 구문을 작성할 수 있다. 다시 던지기 함수나 메서드가 오류를 던지는 함수를 do-catch 구문 내부에서 호출하고 catch 절 내부에서 다른 오류를 던짐으로써 오류를 던지는 함수에서 발생한 오류를 제어할 수 있다. 다시 던지기 내부의 catch 절에서는 다시 던지기 함수의 매개변수로 전달받은 오류던지기 함수만 호출하고 결과로 다져진 오류만 제어할 수 있다.
- 부모클래스의 다시 던지기 메서드(rethrows 메서드)는 자식클래스에서 던지기 메서드로 재정의할 수 없다. 그러나 부모클래스의 던지기 메서드는 자식클래스에서 다시 던지기 메서드로 재정의할 수 있다. 그리고 만약 프로토콜 요구사항 중에 다시 던지기 메서드가 있다면, 던지기 메서드를 구현한다고 해서 요구사항을 충족시킬 수는 없다. 그러나 프로토콜 요구사항 중에 던지기 메서드가 있다면 다시 던지기 메서드를 구현해서 요구사항을 충족시킬 수 있다. 
- 던지기 메서드는 다시 던지기 메서드 요구에 부합하지만 다시 던지기 메서드는 던지기 메서드 요구에 부합하지 못한다. 또, 부모클래스의 던지기 메서드는 자식클래스에서 다시 던지기 메서드로 재정의할 수 있는 반면, 부모클래스의 던지기 메서드는 자식클래스의 던지기 메서드로 재정의할 수 없다. 
